# Run in container-based environment
sudo: false

# Install the build requirements
addons:
  apt:
    packages:
    - build-essential

# Environment
env:
 - OPTIMSOC=/$HOME/optimsoc

# Execute the build
script:
  - ./tools/install.py -d $OPTIMSOC
