# Run in container-based environment
sudo: false

# Install the build requirements
addons:
  apt:
    packages:
    - build-essential

# Environment
env:
 global:
  - OPTIMSOC=$HOME/optimsoc/current
  - PATH=$HOME/optimsoc/toolchains/or1k-elf-multicore/bin:$PATH
  - LD_LIBRARY_PATH=$HOME/optimsoc/toolchains/or1k-elf-multicore/x86_64-unknown-linux-gnu/or1k-elf/lib

before_install:
 - mkdir -p $HOME/optimsoc/toolchains
 - curl http://lis.ei.tum.de/pub-download/openrisc-builds/or1k-elf/dev/or1k-elf-multicore-latest-ubuntu-12.04-amd64.tgz -o $HOME/optimsoc/toolchains/or1k-elf-multicore-latest-ubuntu-12.04-amd64.tgz
 - tar -xzf $HOME/optimsoc/toolchains/or1k-elf-multicore-latest-ubuntu-12.04-amd64.tgz --strip-components=1 -C $HOME/optimsoc/toolchains/

# Execute the build
script:
  - ./tools/install.py -d $OPTIMSOC
